MoviesProject/Models/Film.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MoviesProject.Models
{
    public class Film
    {
        public int Id { get; set; }
        [Required]
        public string Nom { get; set; }
        public string Genre { get; set; }
        [Display(Name = "Date de sortie")]
        public DateTime DateDeSortie { get; set; }
        public string Description { get; set; }
        public virtual List<Commentaire> Commentaires { get; set; }
    }
}

MoviesProject/Controllers/CommentaireController.cs
using MoviesProject.Models;
using MoviesProject.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MoviesProject.Controllers
{
    public class CommentaireController : Controller
    {
        private IDal dal;

        public CommentaireController() : this(new Dal()) 
        {
        }

        public CommentaireController(IDal dal)
        {
            this.dal = dal;
        }

        public ActionResult CreerCommentaire(int? id)
        {
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                Utilisateur utilisateur = dal.RecupererUtilisateur(HttpContext.User.Identity.Name);
                if (utilisateur.Role == "ADMIN" || utilisateur.Role == "USER")
                {
                    ViewBag.nomFilm = dal.RecupererFilm(id.Value).Nom;
                    return View();
                }
            }

            return RedirectToAction("Index", "Film");
        }

        [HttpPost]
        public ActionResult CreerCommentaire(int? id, Commentaire commentaire)
        {
            if (!ModelState.IsValid)
                return View(commentaire);

            Utilisateur utilisateur = dal.RecupererUtilisateur(HttpContext.User.Identity.Name);
            dal.AjouterCommentaire(commentaire.Contenu, utilisateur.Id, id.Value);

            return RedirectToAction("Index", "Film");
        }
    }
}

MoviesProject/Controllers/FilmController.cs
using MoviesProject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MoviesProject.Controllers
{
    public class FilmController : Controller
    {
        private IDal dal;

        public FilmController() : this(new Dal())
        {
        }

        public FilmController(IDal dal)
        {
            this.dal = dal;
        }

        public ActionResult Index()
        {
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                IDal dal = new Dal();
                Utilisateur utilisateur = dal.RecupererUtilisateur(HttpContext.User.Identity.Name);
                ViewBag.role = utilisateur.Role;
            }

            List<Film> listeDesFilms = dal.RecupererTousLesFilms();
            return View(listeDesFilms);
        }

        public ActionResult VoirFilm(string nomFilm)
        {
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                IDal dal = new Dal();
                Utilisateur utilisateur = dal.RecupererUtilisateur(HttpContext.User.Identity.Name);
                ViewBag.role = utilisateur.Role;
            }

            Film film = dal.RecupererFilm(nomFilm);
            return View(film);
        }

        public ActionResult CreerFilm()
        {
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                Utilisateur utilisateur = dal.RecupererUtilisateur(HttpContext.User.Identity.Name);
                if (utilisateur.Role == "ADMIN")
                    return View();
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult CreerFilm(Film film)
        {
            if (dal.FilmExisteDeja(film.Nom))
            {
                ModelState.AddModelError("Nom", "Ce film existe déjà");
                return View(film);
            }
            if (!ModelState.IsValid)
                return View(film);

            dal.CreerFilm(film.Nom, film.Genre, film.DateDeSortie, film.Description);

            return RedirectToAction("Index");
        }

        public ActionResult ModifierFilm(int? id)
        {
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                Utilisateur utilisateur = dal.RecupererUtilisateur(HttpContext.User.Identity.Name);
                if (utilisateur.Role == "ADMIN")
                {
                    if (id.HasValue)
                    {
                        Film film = dal.RecupererTousLesFilms().FirstOrDefault(r => r.Id == id.Value);
                        if (film == null)
                            return View("Error");

                        return View(film);
                    }
                }       
            }
            return HttpNotFound();
        }

        [HttpPost]
        public ActionResult ModifierFilm(Film film)
        {
            if (!ModelState.IsValid)
                return View(film);
            dal.ModifierFilm(film.Id, film.Nom, film.Genre, film.DateDeSortie, film.Description);

            return RedirectToAction("Index");
        }

        public ActionResult SupprimerFilm(int? id)
        {
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                Utilisateur utilisateur = dal.RecupererUtilisateur(HttpContext.User.Identity.Name);
                if (utilisateur.Role == "ADMIN")
                {
                    if (id.HasValue)
                    {
                        dal.SupprimerFilm(id.Value);
                    }
                }    
            }
            
            return RedirectToAction("Index");
        }
    }
}

MoviesProject/Views/Film/CreerFilm.cshtml
@model MoviesProject.Models.Film

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Ajouter Film";
}

<div class="container">
    <div class="row">
        <div class="col-lg-offset-2 col-lg-8">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4>Ajouter un film</h4>
                </div>
                <div class="panel-body">
                    @using (Html.BeginForm())
                    {
                        <div class="form-group">
                            @Html.LabelFor(model => model.Nom)
                            @Html.TextBoxFor(model => model.Nom, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Nom)
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Genre)
                            @Html.TextBoxFor(model => model.Genre, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Genre)
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.DateDeSortie)
                            @Html.TextBoxFor(model => model.DateDeSortie, new { type = "date", @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.DateDeSortie)
                        </div>
                        <div>
                            @Html.LabelFor(model => model.Description)
                            @Html.TextAreaFor(model => model.Description, new { @class = "form-control", rows = "4" })
                            @Html.ValidationMessageFor(model => model.Description)
                        </div>
                        <br />
                        <input type="submit" value="Ajouter" class="btn btn-primary" />
                    }
                </div>
            </div>
        </div>
    </div>
</div>

MoviesProject/Views/Film/Index.cshtml
@model List<MoviesProject.Models.Film>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Les films";
}

<div class="container">
    <div class="row">

        @using (Html.BeginForm("VoirFilm", "Film", FormMethod.Get, new { @class = "form-inline" }))
            {
            <div class="form-group">
                <label for="recherche">Recherche film :</label>
                <input type="text" id="recherche" name="nomFilm" class="form-control" />
            </div>
                <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
                <br /><br />
        }

        @{
            foreach (var film in Model)
            {
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <b>@film.Nom</b> 
                            @if (ViewBag.role == "ADMIN")
                            {
                                @Html.ActionLink("Modifier", "ModifierFilm", "Film", new { id = film.Id }, new { @class = "btn btn-warning" });
                                @Html.ActionLink("Supprimer", "SupprimerFilm", "Film", new { id = film.Id }, new { @class = "btn btn-danger" });
                            }
                        </div>

                        <div class="panel-body">
                            <p>
                                <b>Description :</b><br>
                                @film.Description
                            </p>
                            <p>
                                <b>Genre : </b>@film.Genre - <b>Date de sortie : </b>@film.DateDeSortie.ToString("dd MMM yyyy")
                            </p>

                            <p><b>Commentaires :</b></p>
                            @foreach(var commentaire in film.Commentaires)
                            {
                                <div class="well well-sm">
                                    <p>
                                        <i>@commentaire.Utilisateur.NomUtilisateur</i><br />
                                        @commentaire.Contenu
                                    </p>
                                </div>
                                
                            }

                            
                            @if (ViewBag.role == "ADMIN" || ViewBag.role == "USER")
                            {
                                @Html.ActionLink("Ajouter un commentaire", "CreerCommentaire", "Commentaire", new { id = film.Id }, new { @class = "btn btn-default" });
                            }

                        </div>
                    </div>
                </div>
            }
        }
    </div>
</div>

MoviesProject/Views/Film/ModifierFilm.cshtml
@model MoviesProject.Models.Film

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Modifier Film";
}

<div class="container">
    <div class="row">
        <div class="col-lg-offset-2 col-lg-8">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4>Modifier un film</h4>
                </div>
                <div class="panel-body">
                    @using (Html.BeginForm())
                    {
                        <div class="form-group">
                            @Html.LabelFor(model => model.Nom)
                            @Html.TextBoxFor(model => model.Nom, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Nom)
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Genre)
                            @Html.TextBoxFor(model => model.Genre, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Genre)
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.DateDeSortie)
                            @Html.TextBoxFor(model => model.DateDeSortie, new { type = "date", @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.DateDeSortie)
                        </div>
                        <div>
                            @Html.LabelFor(model => model.Description)
                            @Html.TextAreaFor(model => model.Description, new { @class = "form-control", rows = "4" })
                            @Html.ValidationMessageFor(model => model.Description)
                        </div>
                        <br />
                        <input type="submit" value="Modifier" class="btn btn-primary" />
                    }
                </div>
            </div>
        </div>
    </div>
</div>

MoviesProject/Views/Film/VoirFilm.cshtml
@model MoviesProject.Models.Film

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Film";
}

<div class="container">
    <div class="row">
        <div class="col-lg-12">

            @using (Html.BeginForm("VoirFilm", "Film", FormMethod.Get, new { @class = "form-inline" }))
            {
                <div class="form-group">
                    <label for="recherche">Recherche film :</label>
                    <input type="text" id="recherche" name="nomFilm" class="form-control" /> 
                </div>
                <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
                <br /><br />
            }

            @if (Model == null)
            {
                <h1>Aucun film a été trouvé !</h1>
            }
            else
            {
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <b>@Model.Nom</b>
                    </div>

                    <div class="panel-body">
                        <p>
                            <b>Description :</b><br>
                            @Model.Description
                        </p>
                        <p>
                            <b>Genre : </b>@Model.Genre - <b>Date de sortie : </b>@Model.DateDeSortie.ToString("dd MMM yyyy")
                        </p>

                        <p><b>Commentaires :</b></p>
                        @foreach (var commentaire in Model.Commentaires)
                        {
                            <div class="well well-sm">
                                <p>
                                    <i>@commentaire.Utilisateur.NomUtilisateur</i><br />
                                    @commentaire.Contenu
                                </p>
                            </div>

                        }
                    </div>
                </div>
            }
            @Html.ActionLink("Retour", "Index", "Film", new { @class = "btn btn-default" })
        </div>
    </div>
</div>