MoviesProject/Controllers/AccueilController.cs
using MoviesProject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MoviesProject.Controllers
{
    public class AccueilController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                IDal dal = new Dal();
                Utilisateur utilisateur = dal.RecupererUtilisateur(HttpContext.User.Identity.Name);
                ViewBag.nom = utilisateur.NomUtilisateur;
                ViewBag.role = utilisateur.Role;
            }
            else
            {
                ViewBag.nom = "Anonyme";
                ViewBag.role = "";
            }

            return View();
        }
    }
}

MoviesProject/Controllers/ConnexionController.cs
using MoviesProject.Models;
using MoviesProject.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace MoviesProject.Controllers
{
    public class ConnexionController : Controller
    {
        private IDal dal;

        public ConnexionController() : this(new Dal()) {}

        private ConnexionController(IDal dal)
        {
            this.dal = dal;
        }

        public ActionResult Index()
        {
            UtilisateurViewModel viewModel = new UtilisateurViewModel { Authentifie = HttpContext.User.Identity.IsAuthenticated };
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                viewModel.Utilisateur = dal.RecupererUtilisateur(HttpContext.User.Identity.Name);
            }

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Index(UtilisateurViewModel viewModel, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                Utilisateur utilisateur = dal.Authentifier(viewModel.Utilisateur.NomUtilisateur, viewModel.Utilisateur.MotDePasse);
                if (utilisateur != null)
                {
                    FormsAuthentication.SetAuthCookie(utilisateur.Id.ToString(), false);
                    if (!string.IsNullOrWhiteSpace(returnUrl) && Url.IsLocalUrl(returnUrl))
                        return Redirect(returnUrl);
                    return Redirect("/");
                }
                ModelState.AddModelError("Utilisateur.NomUtilisateur", "Nom d'utilisateur et/ou mot de passe incorrect(s)");
            }

            return View(viewModel);
        }

        public ActionResult CreerCompte()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreerCompte(Utilisateur utilisateur)
        {
            if (ModelState.IsValid)
            {
                int id = dal.AjouterUtilisateur(utilisateur.NomUtilisateur, utilisateur.MotDePasse, "USER");
                FormsAuthentication.SetAuthCookie(id.ToString(), false);
                return Redirect("/");
            }
            return View(utilisateur);
        }

        public ActionResult Deconnexion()
        {
            FormsAuthentication.SignOut();
            return Redirect("/");
        }
    }
}

MoviesProject/Controllers/FilmController.cs
using MoviesProject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MoviesProject.Controllers
{
    public class FilmController : Controller
    {
        private IDal dal;

        public FilmController() : this(new Dal())
        {
        }

        public FilmController(IDal dal)
        {
            this.dal = dal;
        }

        public ActionResult Index()
        {
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                IDal dal = new Dal();
                Utilisateur utilisateur = dal.RecupererUtilisateur(HttpContext.User.Identity.Name);
                ViewBag.role = utilisateur.Role;
            }

            List<Film> listeDesFilms = dal.RecupererTousLesFilms();
            return View(listeDesFilms);
        }

        public ActionResult VoirFilm(string nomFilm)
        {
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                IDal dal = new Dal();
                Utilisateur utilisateur = dal.RecupererUtilisateur(HttpContext.User.Identity.Name);
                ViewBag.role = utilisateur.Role;
            }

            Film film = dal.RecupererFilm(nomFilm);
            return View(film);
        }

        public ActionResult CreerFilm()
        {
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                Utilisateur utilisateur = dal.RecupererUtilisateur(HttpContext.User.Identity.Name);
                if (utilisateur.Role == "ADMIN")
                    return View();
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult CreerFilm(Film film)
        {
            if (dal.FilmExisteDeja(film.Nom))
            {
                ModelState.AddModelError("Nom", "Ce film existe déjà");
                return View(film);
            }
            if (!ModelState.IsValid)
                return View(film);

            dal.CreerFilm(film.Nom, film.Genre, film.DateDeSortie, film.Description);

            return RedirectToAction("Index");
        }

        public ActionResult ModifierFilm(int? id)
        {
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                Utilisateur utilisateur = dal.RecupererUtilisateur(HttpContext.User.Identity.Name);
                if (utilisateur.Role == "ADMIN")
                {
                    if (id.HasValue)
                    {
                        Film film = dal.RecupererTousLesFilms().FirstOrDefault(r => r.Id == id.Value);
                        if (film == null)
                            return View("Error");

                        return View(film);
                    }
                }       
            }
            return HttpNotFound();
        }

        [HttpPost]
        public ActionResult ModifierFilm(Film film)
        {
            if (!ModelState.IsValid)
                return View(film);
            dal.ModifierFilm(film.Id, film.Nom, film.Genre, film.DateDeSortie, film.Description);

            return RedirectToAction("Index");
        }

        public ActionResult SupprimerFilm(int? id)
        {
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                Utilisateur utilisateur = dal.RecupererUtilisateur(HttpContext.User.Identity.Name);
                if (utilisateur.Role == "ADMIN")
                {
                    if (id.HasValue)
                    {
                        dal.SupprimerFilm(id.Value);
                    }
                }    
            }
            
            return RedirectToAction("Index");
        }
    }
}

MoviesProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link type="text/css" rel="stylesheet" href="~/Content/bootstrap/css/bootstrap.min.css" />
    <link type="text/css" rel="stylesheet" href="~/Content/css/general.css" />
</head>

<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("AnalyseCiné", "Index", "Accueil", null, new { @class = "navbar-brand" })
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Accueil", "Index", "Accueil")</li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Films <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Voir les films", "Index", "Film")</li>
                            <li>@Html.ActionLink("Chercher un film", "VoirFilm", "Film")</li>
                            <li>@Html.ActionLink("Ajouter un film", "CreerFilm", "Film")</li>
                        </ul>
                    </li>
                </ul>
                @using (Html.BeginForm("VoirFilm", "Film", FormMethod.Get, new { @class = "navbar-form navbar-left", @id = "navbar-recherche" }))
                {
                    <div class="form-group">
                        <input type="text" id="recherche" name="nomFilm" class="form-control" placeholder="nom d'un film" />
                    </div>
                    <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
                }
                @Html.ActionLink("Se connecter", "Index", "Connexion", null, new { @class = "btn btn-default navbar-btn" })
            </div>

        </div>
    </nav>

    @RenderBody()

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="~/Content/bootstrap/js/bootstrap.min.js"></script>
</body>

</html>